### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Hybried8** [sugarlabs/cellgame#17]
Hi!

I came across this and found out the description was rather lacking. I would like to fill it in if possible

**Comment by quozl** [comment]
Thanks, but if you would like to do this please;

* don't create an issue, but a pull request, and;
* use the existing pull request and discussion as basis, see https://github.com/sugarlabs/cellgame/pull/16, and if you don't or can't use it then make sure you explain why that is,

At Sugar Labs, issues are for recording faults or problems that you don't plan to fix.  They are a work request for a volunteer response.  It makes no sense to create an issue that _you_ plan to fix.  Just fix whatever it is you want to fix.

If someone has told you we welcome issues in the way you have done it, please let them know they are wrong.  Thanks.

**Comment by Hybried8** [comment]
@quozl apologies for any inconvenience caused and thank you so much for the information.
