### ISSUE TITLE
Port to python 3.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/cellgame#5]

**Comment by JuiP** [comment]
I think with #9 merged, we can close this issue now?

**Comment by chimosky** [comment]
Yeah thanks.

**Comment by quozl** [comment]
Our failure to close this issue after merging https://github.com/sugarlabs/cellgame/pull/9 did [cause wasted effort by a college team](https://github.com/CSCI-462-01-2020/Lab-Rats/blob/master/LabRats_poster.pdf).  It shows we aren't the only ones affected by our inactions.
